name: "Pull Request Labeller"
on:
  - pull_request_target

jobs:
  triage:
    permissions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
